apiVersion: v1
kind: Pod
metadata:
  name: oom-demo
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - name: stress
    image: polinux/stress
    command: ["stress", "--vm", "1", "--vm-bytes", "{{ .Values.app.stressBytes }}", "--timeout", "3600"]
    resources:
      requests:
        memory: {{ .Values.resources.requests.memory | quote }}
      limits:
        memory: {{ .Values.resources.limits.memory | quote }}
