apiVersion: v1
kind: Pod
metadata:
  name: storage-app
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - name: app
    image: nginx:alpine
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: expand-pvc
