apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expand-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if ne .Values.pvc.storageClassName "" }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
