apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loader-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs:
  {{- range .Values.rbac.verbs }}
  - {{ . | quote }}
  {{- end }}
