apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
      - name: app
        image: nginx:alpine
        ports:
        - containerPort: 8080
