apiVersion: v1
kind: Service
metadata:
  name: discovery-svc
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  selector:
    app: discovery
  ports:
  - port: 80
    targetPort: 8080
