apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  name: {{ .Values.config.dbName | quote }}
  redis_url: {{ .Values.config.redisUrl | quote }}
  new_feature_flag: {{ .Values.config.newFeatureFlag | quote }}
  {{- if .Values.config.cacheTtl }}
  cache_ttl: {{ .Values.config.cacheTtl | quote }}
  {{- end }}
