apiVersion: v1
kind: Service
metadata:
  name: dns-app
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    app: dns-app
  ports:
  - port: 80
    targetPort: 80
