apiVersion: v1
kind: Pod
metadata:
  name: web-ready
  labels:
    app: web
spec:
  containers:
  - name: nginx
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: {{ .Values.probe.path }}
        port: {{ .Values.probe.port }}
      periodSeconds: 10
      failureThreshold: 3
